# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-24 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('gtfs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Company'),
        ),
        migrations.AddField(
            model_name='trip',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_route', related_query_name='trip_route', to='gtfs.Route'),
        ),
        migrations.AddField(
            model_name='trip',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtfs.Calendar'),
        ),
        migrations.AddField(
            model_name='stoptime',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Company'),
        ),
        migrations.AddField(
            model_name='stop',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Company'),
        ),
        migrations.AddField(
            model_name='stop',
            name='parent_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtfs.Stop'),
        ),
        migrations.AddField(
            model_name='route',
            name='agency',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gtfs.Agency'),
        ),
        migrations.AddField(
            model_name='route',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Company'),
        ),
        migrations.AddField(
            model_name='frequency',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Company'),
        ),
        migrations.AddField(
            model_name='frequency',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtfs.Trip'),
        ),
        migrations.AddField(
            model_name='farerule',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Company'),
        ),
        migrations.AddField(
            model_name='farerule',
            name='fare',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtfs.FareAttribute'),
        ),
        migrations.AddField(
            model_name='farerule',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farerule_route', to='gtfs.Route'),
        ),
        migrations.AddField(
            model_name='fareattribute',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fare_agency', to='gtfs.Agency'),
        ),
        migrations.AddField(
            model_name='fareattribute',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Company'),
        ),
        migrations.AddField(
            model_name='calendardate',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Company'),
        ),
        migrations.AddField(
            model_name='calendardate',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtfs.Calendar'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Company'),
        ),
        migrations.AddField(
            model_name='agency',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Company'),
        ),
    ]
