# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-25 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0002_auto_20180524_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='fare_url',
            field=models.CharField(blank=True, max_length=240, verbose_name='Agency URL'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='lang',
            field=models.CharField(blank=True, max_length=10, verbose_name='Agency Language'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Agency Phone'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='timezone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Agency Timezone'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='url',
            field=models.CharField(blank=True, max_length=240, verbose_name='Agency URL'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='service_id',
            field=models.CharField(max_length=25, unique=True, verbose_name='service_id'),
        ),
        migrations.AlterField(
            model_name='stop',
            name='parent_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gtfs.Stop'),
        ),
        migrations.AlterField(
            model_name='stop',
            name='stop_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='Stop code'),
        ),
        migrations.AlterField(
            model_name='stop',
            name='stop_desc',
            field=models.CharField(blank=True, max_length=500, verbose_name='Stop code'),
        ),
        migrations.AlterField(
            model_name='stop',
            name='stop_timezone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Stop timezone'),
        ),
        migrations.AlterField(
            model_name='stop',
            name='zone_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Zone ID'),
        ),
    ]
