# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-25 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20180525_2236'),
        ('gtfs', '0004_auto_20180526_0016'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stop',
            unique_together=set([('company', 'stop_id')]),
        ),
    ]
