# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-25 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20180525_2236'),
        ('gtfs', '0005_auto_20180526_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='route_id',
            field=models.CharField(max_length=25, verbose_name='route_id'),
        ),
        migrations.AlterUniqueTogether(
            name='agency',
            unique_together=set([('company', 'agency_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='calendar',
            unique_together=set([('company', 'service_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='fareattribute',
            unique_together=set([('company', 'fare_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together=set([('company', 'route_id')]),
        ),
    ]
