# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-01 04:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0006_auto_20180526_0108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ('agency', 'route_id')},
        ),
        migrations.AlterModelOptions(
            name='stoptime',
            options={'ordering': ['trip', 'stop', 'sequence'], 'verbose_name_plural': 'Stop times'},
        ),
        migrations.RemoveField(
            model_name='stoptime',
            name='long_name',
        ),
        migrations.RemoveField(
            model_name='stoptime',
            name='short_name',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='long_name',
        ),
        migrations.AddField(
            model_name='stoptime',
            name='arrival',
            field=models.TimeField(default='00:00', verbose_name='Arrival time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stoptime',
            name='departure',
            field=models.TimeField(default='00:00', verbose_name='Arrival time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stoptime',
            name='drop_off_type',
            field=models.CharField(choices=[('0', 'Regularly scheduled drop off'), ('1', 'No drop off available'), ('2', 'Must phone agency to arrange drop off'), ('3', 'Must coordinate with driver to arrange drop off')], default='0', max_length=1, verbose_name='Drop off type'),
        ),
        migrations.AddField(
            model_name='stoptime',
            name='pickup_type',
            field=models.CharField(choices=[('0', 'Regularly scheduled pickup'), ('1', 'No pickup available'), ('2', 'Must phone agency to arrange pickup'), ('3', 'Must coordinate with driver to arrange pickup')], default='0', max_length=1, verbose_name='Pickup type'),
        ),
        migrations.AddField(
            model_name='stoptime',
            name='sequence',
            field=models.IntegerField(default=0, verbose_name='Stop sequence'),
        ),
        migrations.AddField(
            model_name='stoptime',
            name='shape_dist_traveled',
            field=models.CharField(blank=True, max_length=5, verbose_name='Travel distance in km'),
        ),
        migrations.AddField(
            model_name='stoptime',
            name='stop',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gtfs.Stop'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stoptime',
            name='stop_headsign',
            field=models.CharField(blank=True, max_length=30, verbose_name='Stop headsign'),
        ),
        migrations.AddField(
            model_name='stoptime',
            name='timepoint',
            field=models.CharField(choices=[('', 'Times are considered exact.'), ('0', 'Times are considered approximate.'), ('1', 'Times are considered exact.')], default='', max_length=1, verbose_name='Timepoint'),
        ),
        migrations.AddField(
            model_name='trip',
            name='bike_allowed',
            field=models.CharField(choices=[('', 'indicates that there is no bike information for the trip'), ('0', 'indicates that there is no bike information for the trip'), ('1', 'indicates that the vehicle being used on this particular trip can accommodate at least one bicycle'), ('2', 'No bicycles are allowed on this trip')], default='', max_length=1, verbose_name='Wheelchair accessible'),
        ),
        migrations.AddField(
            model_name='trip',
            name='block_id',
            field=models.CharField(blank=True, max_length=15, verbose_name='Block ID'),
        ),
        migrations.AddField(
            model_name='trip',
            name='direction_id',
            field=models.CharField(choices=[('0', 'travel in one direction (e.g. outbound travel)'), ('1', 'travel in the opposite direction (e.g. inbound travel)')], default='', max_length=1, verbose_name='long name'),
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_headsign',
            field=models.CharField(blank=True, max_length=30, verbose_name='Trip headsign'),
        ),
        migrations.AddField(
            model_name='trip',
            name='wheelchair_accessible',
            field=models.CharField(choices=[('', 'No wheelchair accessibility'), ('0', 'No wheelchair accessibility'), ('1', 'indicates that the vehicle being used on this particular trip can accommodate at least one rider in a wheelchair'), ('2', 'No riders in wheelchairs can be accommodated on this trip')], default='', max_length=1, verbose_name='Wheelchair accessible'),
        ),
        migrations.AlterField(
            model_name='stoptime',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtfs.Trip'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='short_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Trip short name'),
        ),
    ]
