# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-01 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0007_auto_20180601_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stoptime',
            name='departure',
            field=models.TimeField(verbose_name='Departure time'),
        ),
    ]
