# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0008_auto_20180601_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='direction_id',
            field=models.CharField(choices=[('0', 'travel in one direction (e.g. outbound travel)'), ('1', 'travel in the opposite direction (e.g. inbound travel)')], default='', max_length=1, verbose_name='Direction'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtfs.Route'),
        ),
    ]
