# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0009_auto_20180605_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequency',
            name='headway_secs',
            field=models.IntegerField(default=1800, verbose_name='Headway seconds'),
        ),
    ]
