# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-01 02:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0011_auto_20180805_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='farerule',
            name='contains_id',
            field=models.CharField(default='', max_length=100, verbose_name='Contains ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farerule',
            name='destination_id',
            field=models.CharField(default='', max_length=100, verbose_name='Destination ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farerule',
            name='origin_id',
            field=models.CharField(default='', max_length=100, verbose_name='Origin ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='farerule',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gtfs.Route'),
        ),
    ]
