# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-15 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0012_auto_20181001_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fareattribute',
            name='transfer_duration',
            field=models.CharField(max_length=4, verbose_name='Transfer duration'),
        ),
    ]
