# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-19 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0014_auto_20181015_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farerule',
            name='origin_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Origin ID'),
        ),
    ]
