# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-17 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0015_auto_20181019_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequency',
            name='end_time',
            field=models.CharField(max_length=9, verbose_name='End time'),
        ),
        migrations.AlterField(
            model_name='frequency',
            name='start_time',
            field=models.CharField(max_length=9, verbose_name='Start time'),
        ),
    ]
