# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-05 03:13
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='POI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gd_id', models.CharField(blank=True, max_length=50, verbose_name='GoodWalk ID')),
                ('name', models.CharField(max_length=500, verbose_name='Name')),
                ('branch', models.CharField(blank=True, max_length=200, verbose_name='Branch')),
                ('category', models.CharField(max_length=50, verbose_name='Category')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Location')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated on')),
            ],
        ),
    ]
