# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible
from django.contrib.gis.db.models import (
    Model, CharField, IntegerField, DateField, BooleanField, ForeignKey,
    MultiPolygonField, EmailField, PointField, DecimalField, TimeField,
)
from django.utils import timezone


class CompanyBoundModel(Model):
    company = ForeignKey('people.Company')

    class Meta:
        abstract = True


@python_2_unicode_compatible
class Agency(CompanyBoundModel):
    """Transit agencies that provide the data in this feed.

    """
    agency_id = CharField('agency_id', max_length=25)
    name = CharField('Agency Name', max_length=500)
    url = CharField('Agency URL', max_length=240)
    timezone = CharField('Agency Timezone', max_length=50)
    phone = CharField('Agency Phone', max_length=50)
    lang = CharField('Agency Language', max_length=10)
    fare_url = CharField('Agency URL', max_length=240)
    email = EmailField('Email', blank=True)

    class Meta:
        verbose_name_plural = "agencies"

    def __str__(self):
        return self.agency_id



@python_2_unicode_compatible
class Stop(CompanyBoundModel):
    """Individual locations where vehicles pick up or drop off passengers.

    "stop_id", "stop_code", "stop_name", "stop_desc", "stop_lat",
		"stop_lon", "zone_id", "stop_url", "location_type", "parent_station",
		"direction", "position"

    stop_id,stop_name,stop_desc,stop_lat,stop_lon,stop_url,location_type,parent_station

    """
    stop_id = CharField('stop_id', max_length=25)
    name = CharField('name', max_length=500)
    location = PointField('Location')
    # optinal
    stop_code = CharField('Stop code', max_length=100)
    stop_desc = CharField('Stop code', max_length=500)
    zone_id = CharField('Zone ID', max_length=100)
    LOCATION_TYPES = (
        ('0', 'Stop'),
        ('1', 'Station'),
        ('2', 'Station Entrance/Exit'),
    )
    location_type = CharField('Location types', max_length=1,
                              default='0', choices=LOCATION_TYPES)
    parent_station = ForeignKey('Stop')
    stop_timezone = CharField('Stop timezone', max_length=20)
    WHEELCHAIR_CHOICES = (
        ('0', 'No wheelchair accessibility'),
        ('1', 'at least some vehicles at this stop can be boarded ' \
              'by a rider in a wheelchair'),
        ('2', 'wheelchair boarding is not possible at this stop'),
    )
    wheelchair_boarding = CharField('Wheelchair boarding', max_length=1,
                                    default='0', choices=WHEELCHAIR_CHOICES)

    def __str__(self):
        return self.stop_id


@python_2_unicode_compatible
class Route(CompanyBoundModel):
    """Transit routes. A route is a group of trips that are displayed to riders
    as a single service.

    # GTFS Feed

    ## routes.txt

    This is obvious, basic fields

        "route_id", "agency_id", "route_short_name", "route_long_name",
		"route_desc", "route_type", "route_url", "route_color",
		"route_text_color"

    ## shapes.txt

    This is generated by `self.shapes` for `trips.txt`
    
    ### required
    
    shape_id,
    shape_pt_lat,
    shape_pt_lon,
    shape_pt_sequence,

    ### optional 
    
    shape_dist_traveled (in km)


    """
    route_id = CharField('route_id', max_length=25, unique=True)
    short_name = CharField('short name', max_length=150)
    long_name = CharField('long name', max_length=500)
    shapes = MultiPolygonField(srid=4326, null=True, blank=True)

    agency = ForeignKey('Agency', blank=True)
    desc = CharField('Route desc', max_length=250)
    ROUTE_TYPES = (
        ('0', 'Tram, Streetcar, Light rail'),
        ('1', 'Subway, Metro. Any underground rail system ' \
              'within a metropolitan area.'),
        ('2', 'Rail'),
        ('3', 'Bus'),
        ('4', 'Ferry'),
        ('5', 'Cable car'),
        ('6', 'Gondola, Suspended cable car'),
        ('7', 'Funicular. Any rail system designed for steep inclines.'),
    )
    route_type = CharField('Route type', max_length=1,
                           default='2', choices=ROUTE_TYPES)
    route_url = CharField('Route URL', max_length=240)
    route_color = CharField('Route color', max_length=6)
    route_text_color = CharField('Route text color', max_length=6)
    route_sort_order = IntegerField('Route sort order', default=0)

    def __str__(self):
        return self.route_id


@python_2_unicode_compatible
class StopTime(CompanyBoundModel):
    """
    "trip_id", "arrival_time", "departure_time", "stop_id", "stop_sequence",
		"stop_headsign", "pickup_type", "drop_off_type", "shape_dist_traveled",
		"timepoint", "continuous_drop_off", "continuous_pickup"

    """
    trip = CharField('route_id', max_length=25)
    short_name = CharField('short name', max_length=150)
    long_name = CharField('long name', max_length=500)

    class Meta:
        verbose_name_plural = "Stop times"

    def __str__(self):
        return '%s' % self.pk


@python_2_unicode_compatible
class Calendar(CompanyBoundModel):
    """This indicates normal service set
    """
    service_id = CharField('agency_id', max_length=25, unique=True)
    start_date = DateField('Start Date', default=timezone.now)
    end_date = DateField('Start Date', default=timezone.now)
    monday = BooleanField('Monday', default=False)
    tuesday = BooleanField('Tuesday', default=False)
    wednesday = BooleanField('Wednesday', default=False)
    thursday = BooleanField('Thursday', default=False)
    friday = BooleanField('Friday', default=False)
    saturday = BooleanField('Saturday', default=False)
    sunday = BooleanField('Sunday', default=False)

    def __str__(self):
        return self.service_id


@python_2_unicode_compatible
class CalendarDate(CompanyBoundModel):
    """This is an exception for Calendar
    """
    EXCEPTION_TYPES = (
        ('1', 'Add to service'),
        ('2', 'Remove from service'),
    )
    service = ForeignKey(Calendar)
    date = DateField('Date')
    exception_type = CharField('Exception Type', max_length=1,
                               default='2',
                               choices=EXCEPTION_TYPES)

    class Meta:
        verbose_name_plural = "Calendar Dates"

    def __str__(self):
        return '%s-%s' % (self.pk, self.date)


@python_2_unicode_compatible
class Trip(CompanyBoundModel):
    """
    route_id,service_id,trip_id,trip_headsign,block_id
    """
    route = ForeignKey(
        Route,
        related_query_name='trip_route',
        related_name='trip_route',
    )
    service = ForeignKey(Calendar)
    trip_id = CharField('trip_id', max_length=50)
    short_name = CharField('short name', max_length=150)
    long_name = CharField('long name', max_length=500)

    def __str__(self):
        return self.trip_id


@python_2_unicode_compatible
class FareAttribute(CompanyBoundModel):
    """Fare information for a transit organization's routes.

    currency_type          e.g. USD, THB
                           http://en.wikipedia.org/wiki/ISO_4217
    transfer_duration      When used with a transfers value of 0, the
                           transfer_duration field indicates how long a ticket
                           is valid for a fare where no transfers are allowed.
                           Unless you intend to use this field to indicate
                           ticket validity, transfer_duration should be omitted
                           or empty when transfers is set to 0.
    """
    fare_id = CharField('trip_id', max_length=50)
    price = DecimalField('Price', default=0.0, decimal_places=2, max_digits=6)
    currency_type = CharField('Currency type', max_length=3)
    PAYMENT_CHOICES = (
        ('0', 'Fare is paid on board'),
        ('1', 'Fare must be paid before boarding')
    )
    payment_method = CharField('Payment method', max_length=1, default='0',
                               choices=PAYMENT_CHOICES)
    TRANSFER_CHOICES = (
        ('', 'unlimited transfers are permitted.'),
        ('0', 'No transfers permitted on this fare.'),
        ('1', 'Passenger may transfer once.'),
        ('2', 'Passenger may transfer twice.'),
    )
    transfer = CharField('Transfer', max_length=1, default='0',
                         choices=TRANSFER_CHOICES)
    # optional
    agency = ForeignKey('Agency', null=True, blank=True,
        related_name='fare_agency'
    )
    transfer_duration = CharField('Transfer duration', max_length=2)

    def __str__(self):
        return self.pk


@python_2_unicode_compatible
class FareRule(CompanyBoundModel):
    """The fare_rules table allows you to specify how fares in
    fare_attributes.txt apply to an itinerary. Most fare structures use some
    combination of the following rules:

    * Fare depends on origin or destination stations.
    * Fare depends on which zones the itinerary passes through.
    * Fare depends on which route the itinerary uses.

    https://code.google.com/archive/p/googletransitdatafeed/wikis/FareExamples.wiki
    """
    fare = ForeignKey('FareAttribute')

    '''optional

    it's overly complicated for zoning thing
    https://developers.google.com/transit/gtfs/reference/#fare_attributestxt
    '''
    route = ForeignKey('Route', related_name='farerule_route')
    # origin_id = CharField('Origin ID', max_length=100)
    # destination_id = CharField('Destination ID', max_length=100)
    # contains_id = CharField('Contains ID', max_length=100)

    def __str__(self):
        return self.pk


@python_2_unicode_compatible
class Frequency(CompanyBoundModel):
    """Headway (time between trips) for routes with variable frequency of
    service.

    This will be used instead of writing so many stop_times.txt; however,
    transitfeed.ScheduleViewer can't verified or display them yet.

    headway_secs    the time between departures from the same stop (headway)
                    for this trip type, during the time interval specified by
                    start_time and end_time. The headway value must be entered
                    in seconds.
    """
    trip = ForeignKey('Trip')
    start_time = TimeField('Start time')
    end_time = TimeField('End time')
    headway_secs = IntegerField('Headway seconds', )
    # optional
    EXACT_TIME_CHOICES = (
        ('0', 'Frequency-based trips are not exactly scheduled.'),
        ('1', 'Frequency-based trips are exactly scheduled'),
        # For a frequencies.txt row, trips are scheduled starting with
        # trip_start_time = start_time + x * headway_secs for all x in
        # (0, 1, 2, ...) where trip_start_time < end_time.
    )
    exact_times = CharField(
        'Exact times', max_length=1, default='0', choices=EXACT_TIME_CHOICES)

    class Meta:
        verbose_name_plural = "Frequencies"

    def __str__(self):
        return self.pk
